---
title: "R Notebook"
output: html_notebook
---

PRÁCTICA 2, EJERCICIO 1:

```{r}

setwd(".")

list.of.packages <- c("ggplot2", "reshape2", "scales", "dplyr")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)
lapply(list.of.packages, require, character.only=TRUE)

outcome <- read.csv("outcome-of-care-measures.csv")

outcome[,11] <- as.numeric(as.character(outcome[,11]))
min(outcome[,11], na.rm = TRUE)
max(outcome[,11], na.rm=TRUE)
p <- ggplot())
p + geom_XXX() + geom_XXX() + xlab() + ggtitle() + scale_x_continuous(limits = c(10,20))


```


PRÁCTICA 2, EJERCICIO 2:

```{r}

outcomesel <- outcome[,c(11,17,23)]
colnames(outcomesel)[1:3] <- c("Heart_Attack", "Heart_Failure", "Pneumonia")
outcomesel$Heart_Failure <- as.numeric(as.character(outcomesel$Heart_Failure))
outcomesel$Pneumonia <- as.numeric(as.character(outcomesel$Pneumonia))

#melt() outcomesel

p <- ggplot() + geom_XXXX(...) + scale_x_continuous(limits = c(5,20)) + ...
p


```


PRÁCTICA 2, EJERCICIO 3:

```{r}

t <- table(outcome$State)
outcome2 <- subset(outcome, t[outcome$State] > 20)
outcome3 <- subset(outcome2, outcome2[,11] != "Not Available")
p <- ggplot()
p <-p+geom_xxxx()
p <- p + ... + theme(axis.text.x = element_text(angle=90))
p

p1 <- ggplot(, aes(x = reorder(), y = ))
p1 <-p1+....
p1

```

